name: Build

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: $files=(git ls-files src); foreach ($file in $files) { if ((get-item $file).Extension -in ".c", ".h") { &clang-format -i --verbose $file } }; git diff --exit-code

      - name: Build application
        run: make
